-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgC+vdCoGkaEi4uTYC
ViirQd5keZufsm7Lh8ZtC/wCuVCgCgYIKoZIzj0DAQehRANCAAQHPwQk+ZPhWIdp
KTuffrsQe6iJ3wRWcnvqy9TJv4AYq/U1tXbyZqIUidPj0qv84HiHb+Vcw/2i6XTI
CzAVVKeg
-----END PRIVATE KEY-----